services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database_name
    volumes:
      - project-name_pgdata:/var/lib/postgresql/data  # Define volume here
    ports:
      - "5432:5432"

volumes:
  project-name_pgdata:  # Declare the volume here
 